core:
  base_path: "/home/patrick/github/SPACEtomo"

# Model specific settings (depend on how the model was trained)
# WG model (YOLOv8)
detection:
  WG_model_file: "2023_11_16_lamella_detect_400nm_yolo8.pt"
  WG_model_pix_size: 400         # nm / px
  WG_model_sidelen: 1024
  WG_model_categories: ["broken", "contaminated", "good", "thick"]
  WG_model_colors: ["red", "yellow", "green", "orange"]
  WG_model_nav_colors: [0, 2, 1, 3]

# MM model (nnUNet)
segmentation:
  MM_model_script: "SPACEtomo_nnUNet.py"
  MM_model_folder: "model"
  MM_model_folds: [0, 1, 2, 3, 4]
  MM_model_pix_size: 22.83  # nm 
  MM_model_num_pix: 10 
  MM_model_max_runs: 1